#!/usr/bin/env bash
# ShopTalk — deploy into a customer's own infrastructure (PLN-260820 W3).
#
#   bash scripts/deploy-self-hosted.sh            # check, then deploy
#   bash scripts/deploy-self-hosted.sh --check    # check only, change nothing
#   bash scripts/deploy-self-hosted.sh --skip-migration-check   # last resort
#
# Order matters and is enforced here: SQL first, code second. Old code against a
# new column is harmless; new code against an old schema is a 500 on every
# request that touches it (deploy standard 04 §3). This script never applies
# SQL — it stops and tells you what is outstanding.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

COMPOSE_FILE="docker/self-hosted/docker-compose.self-hosted.yml"
ENV_FILE="docker/self-hosted/.env.self-hosted"
CONFIG_FILE="docker/self-hosted/widget-config.js"
export MYSQL_CONTAINER="${MYSQL_CONTAINER:-shoptalk_mysql}"
export API_CONTAINER="${API_CONTAINER:-shoptalk_api}"

check_only=false
skip_migrations=false
for arg in "$@"; do
  case "$arg" in
    --check) check_only=true ;;
    --skip-migration-check) skip_migrations=true ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

step() { printf '\n==> %s\n' "$1"; }

# ---- 1. configuration ------------------------------------------------------
step "Checking configuration"
[[ -f "$ENV_FILE" ]] || {
  echo "ERROR: $ENV_FILE not found." >&2
  echo "       cp docker/self-hosted/.env.self-hosted.example $ENV_FILE" >&2
  echo "       bash scripts/gen-secrets.sh   # fills in the secrets" >&2
  exit 1
}

# UPLOAD_DIR must match the volume mount, or attachments are written inside the
# container and vanish at the next upgrade — without an error, which is what
# makes it worth checking here rather than trusting.
upload_dir="$(grep -E '^UPLOAD_DIR=' "$ENV_FILE" | tail -1 | cut -d= -f2- || true)"
if [[ "$upload_dir" != "/data/uploads" ]]; then
  echo "ERROR: UPLOAD_DIR is '${upload_dir:-unset}', but the compose file mounts the" >&2
  echo "       uploads volume at /data/uploads. Attachments would be written to" >&2
  echo "       container storage and lost on the next deploy." >&2
  exit 1
fi

for required in JWT_ACCESS_SECRET JWT_REFRESH_SECRET CRED_ENC_KEY DB_PASSWORD APP_PUBLIC_URL; do
  value="$(grep -E "^${required}=" "$ENV_FILE" | tail -1 | cut -d= -f2- || true)"
  [[ -n "$value" ]] || { echo "ERROR: $required is empty in $ENV_FILE" >&2; exit 1; }
done
echo "    configuration looks complete"

# ---- 2. widget runtime config ---------------------------------------------
step "Widget runtime config"
api_base="$(grep -E '^VITE_API_BASE_URL=' "$ENV_FILE" | tail -1 | cut -d= -f2- || true)"
[[ -n "$api_base" ]] || { echo "ERROR: VITE_API_BASE_URL is empty in $ENV_FILE" >&2; exit 1; }
if [[ "$check_only" == true ]]; then
  # --check promises to change nothing, and nginx serves this file straight from
  # the host mount: writing it here would repoint a LIVE widget during what the
  # operator was told is a dry run.
  echo "    apiBase would be $api_base (not written in --check mode)"
else
  cat > "$CONFIG_FILE" <<CONFIG
/* Generated by scripts/deploy-self-hosted.sh — do not edit by hand. */
window.__SHOPTALK_CONFIG__ = { apiBase: "${api_base}" };
CONFIG
  echo "    apiBase = $api_base"
fi

# ---- 3. outstanding migrations --------------------------------------------
if [[ "$skip_migrations" == true ]]; then
  echo
  echo "!!  Skipping the migration check. Only do this when you have just applied"
  echo "!!  the SQL by hand and know what is in the database."
elif docker ps --format '{{.Names}}' | grep -qx "$MYSQL_CONTAINER"; then
  step "Checking for outstanding schema migrations"
  if ! bash scripts/check-migrations.sh; then
    echo "Apply the SQL above, then run this script again." >&2
    exit 1
  fi
else
  echo
  echo "    Database container '$MYSQL_CONTAINER' is not running — first install."
  echo "    The schema is created from docker/init-sql on first boot."
fi

if [[ "$check_only" == true ]]; then
  step "Check-only mode: nothing was deployed"
  exit 0
fi

# ---- 4. build and start ----------------------------------------------------
step "Building and starting the stack"
# --env-file is mandatory: without it the VITE_* build args are empty and the
# browser bundles are baked pointing at the wrong API.
docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d --build

# ---- 5. verify -------------------------------------------------------------
step "Verifying"
port="$(grep -E '^HTTP_PORT=' "$ENV_FILE" | tail -1 | cut -d= -f2- || true)"
port="${port:-8080}"

echo -n "    waiting for the API to report healthy "
for _ in $(seq 1 60); do
  if curl -sf "http://localhost:${port}/api/v1/health" >/dev/null 2>&1; then break; fi
  printf '.'
  sleep 5
done
echo

# Exit codes lie about deployments: a container can be up with the previous
# image. Check what the running system actually says (deploy standard 04).
health="$(curl -s "http://localhost:${port}/api/v1/health" || true)"
widget="$(curl -s -o /dev/null -w '%{http_code}' "http://localhost:${port}/widget/" || true)"
console="$(curl -s -o /dev/null -w '%{http_code}' "http://localhost:${port}/" || true)"
# API_CONTAINER, not a hardcoded name: the rehearsal that proved this script
# works ran under different container names and reported "0 boots" for a stack
# that had booted fine.
booted="$(docker logs "${API_CONTAINER:-shoptalk_api}" 2>&1 | grep -c 'successfully started' || true)"

echo "    health   : ${health:-<no answer>}"
echo "    widget   : $widget  (200 expected)"
echo "    console  : $console  (200 expected)"
echo "    boot log : $booted x 'successfully started'"
docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" ps

if [[ "$health" != *'"status":"ok"'* || "$widget" != "200" || "$console" != "200" || "$booted" -lt 1 ]]; then
  echo
  echo "FAIL — the stack started but is not serving. Check: docker logs shoptalk_api" >&2
  exit 1
fi

cat <<'DONE'

Deployed.

Next:
  * Point your TLS terminator at this host's HTTP port.
  * Sign in to the console and change the seeded password.
  * Set up backups:  bash scripts/backup-self-hosted.sh
DONE
